"""
Django settings for discord project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import datetime
from decouple import config
import boto3

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# In settings.py
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# For API-only, you might also want:
ALLOWED_HOSTS = ['13.234.124.118', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "api",
    "room",
    'rest_framework', 
    'rest_framework.authtoken', 
    'rest_framework_simplejwt', 
    "corsheaders",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
     "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'discord.urls'
CORS_ALLOW_CREDENTIALS = True
# CORS_URLS_REGEX=r"^/(api|room)/.*" 
CORS_URLS_REGEX=r"^/(api|room|api/register)/.*"
CORS_ALLOWED_ORIGINS=[
    # "http://localhost:8111/",
    # "https://localhost:8111/",
]


if DEBUG:
  CORS_ALLOWED_ORIGINS +=[
    "http://localhost:5173", # not for production
    "http://localhost:8111", # only allow ssl
    "http://127.0.0.1:5173", 
  ]



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'discord.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


REST_FRAMEWORK={
  'DEFAULT_AUTHENTICATION_CLASSES':[
      'rest_framework.authentication.SessionAuthentication',
          "rest_framework_simplejwt.authentication.JWTAuthentication",
  ],
    "DEFAULT_PERMISSION_CLASSES":[
                   "rest_framework.permissions.IsAuthenticatedOrReadOnly"
  ],
  
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_JWT={
  'AUTH_HEADER_TYPES':["Bearer"],
  "ACCESS_TOKEN_LIFETIME":datetime.timedelta(minutes=15) ,
  "REFRESH_TOKEN_LIFETIME":datetime.timedelta(minutes=45)
}

DEBUG = config('DEBUG', default=False, cast=bool)

ssm=boto3.client('ssm',region_name=os.getenv('AWS_REGION','ap-south-1'))

def get_ssm_param(name):
  return ssm.get_parameter(Name=name,WithDecryption=True)['Parameter']['Value']

AWS_ACCESS_KEY_ID = get_ssm_param('/StudyBud/aws_access_key')
AWS_SECRET_ACCESS_KEY = get_ssm_param('/StudyBud/aws_secret_access_key')
AWS_S3_REGION_NAME = get_ssm_param('/StudyBud/aws_s3_region_name')
AWS_STORAGE_BUCKET_NAME = get_ssm_param('/StudyBud/s3_bucket_name')


